version: '3.1'

services:
  mongo:
    image: mongo
    container_name: dio-mongo-container
    restart: always
    ports:
      - 27017:27017

    volumes:
      - '/Users/Marcos/OneDrive/Área de Trabalho/Meus Projetos/projeto-dio-db-nosql'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dio

  mongo-express:
    image: mongo-express
    container_name: dio-mongo-express
    restart: always
    ports:
      - 8081:8081

    volumes:
      - '/Users/Marcos/OneDrive/Área de Trabalho/Meus Projetos/projeto-dio-db-nosql'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dio
      ME_CONFIG_MONGODB_URL: mongodb://root:dio@mongo:27017/
