name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      
      - name: Build and push images Docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: |
            marcossc20/mongo
  
